name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', dependendo da sua configuração
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ou a versão que você está usando no projeto

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Este é o comando que vai gerar o build do Vite

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Usando o token automático do GitHub
          publish_branch: gh-pages  # A branch para onde o deploy será feito
          publish_dir: dist  # Diretório de saída para o build do Vite
